### ISSUE TITLE
Prisoner no 010101 (pjurczynski) limited access hours.

### ISSUE THREAD

**Issue by pjurczynski** [pjurczynski/inmate_kata#8]
Prisoner got detained and can only rent a computer between 22:00 and 24:00 each day.

During the next week due to special circumstances, his public works on the code can happen between 6:00 and 7:00. Although that's not guaranteed, he might also be a subject of corporal punishment during that time.

**Comment by Greegko** [comment]
I am not sure I can decode what you mean under this statement :D
